# DB
spring:
  datasource:
    url=: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: create