spring:
  datasource:
    url=: jdbc:h2:tcp://localhost/~/audio;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    hibernate:
      ddl-auto: create

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: accesskey
      secretKey: secretkey
    s3:
      bucket: mpt-audio-file-bucket