# DB
spring:
  datasource:
    url=: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

--- #배포 환경
spring.profiles: real
spring.profiles.include: real-db