spring:
  prfiles:
    active: local #기본 로컬 환경

---
spring:
  profiles: local
  datasource:
    url=: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

--- #배포 환경
spring:
  profiles: real
    include: real-db