# DB
spring:
  datasource:
    url=: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

#spring:
#  datasource:
#    url=: jdbc:mysql://audio-database-1.c1lt5pldp7lv.ap-northeast-2.rds.amazonaws.com:3306/audio_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: admin
#    password: 123qwe!!!
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL55Dialect